# -*- coding: utf-8 -*-
"""Emit LaTeX tables and in-text number macros for referee_wp_analysis.tex from the *_v11.json outputs.

Gate G2: no number in the manuscript is typed by hand. The manuscript inputs
`tables_v11.tex` (float environments) and `numbers_v11.tex` (macros used in prose).
Re-running this script after re-running the analysis scripts propagates every number.
"""
import json
import re
from pathlib import Path

ROOT = Path("/Users/satouryuuichi/Desktop/product/hobby/stock_league")
ED = ROOT / "outputs/stockleague_edition"

L1 = json.load(open(ED / "layer1_pit_v11.json"))

SERIES_LABEL = {
    "shu5_roe_only": r"Top 5, ROE rank",
    "buf20_roe_only": r"Top 20, ROE rank",
    "shu5_roe_margin": r"Top 5, ROE${+}$margin rank",
    "buf20_roe_margin": r"Top 20, ROE${+}$margin rank",
    "pool_eq": r"\emph{Entire gate-passing pool}",
}
ORDER = ["shu5_roe_only", "buf20_roe_only", "shu5_roe_margin", "buf20_roe_margin", "pool_eq"]


def pct(x, d=1, sign=False):
    if x is None:
        return "--"
    s = "%+.*f" % (d, x * 100) if sign else "%.*f" % (d, x * 100)
    return s


def num(x, d=2, sign=False):
    if x is None:
        return "--"
    return ("%+.*f" if sign else "%.*f") % (d, x)


# ------------------------------------------------------------------ Table 1
lines = [
    r"% AUTO-GENERATED by scripts/build_wp_tables_v11.py -- do not edit by hand.",
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Layer 1 (out-of-sample).} Forward performance of the quality screen re-formed at "
    r"each as-of date using only filings on file at that date. Equal-weighted, share-count-fixed "
    r"buy-and-hold to 2026-06-01. Benchmark: TOPIX ETF (1306.T).}",
    r"\label{tab:layer1}",
    r"\begin{tabular}{llrrrrrrr}",
    r"\toprule",
    r"As-of & Selection & $n$ & Ann.\ ret. & TOPIX & Excess & Sharpe & MDD & $\beta$ \\",
    r"\midrule",
]
for as_of in L1["as_of_dates"]:
    res = L1["results"][as_of]
    f = L1["funnels"][as_of]
    first = True
    for k in ORDER:
        if k not in res:
            continue
        v = res[k]
        head = (r"\multirow{%d}{*}{\shortstack[l]{%s\\\scriptsize(%d mo.)}}"
                % (len([x for x in ORDER if x in res]), as_of, round(v["days"] / 21)) if first else "")
        lines.append(" & ".join([
            head, SERIES_LABEL[k], str(v["n_selected"]),
            pct(v["ann_return"]) + r"\%", pct(v["bench_ann_return"]) + r"\%",
            pct(v["excess_ann"], sign=True), num(v["sharpe"]), pct(v["max_drawdown"]) + r"\%",
            num(v["beta_vs_bench"]),
        ]) + r" \\")
        first = False
    lines.append(r"\midrule" if as_of != L1["as_of_dates"][-1] else r"\bottomrule")
lines += [
    r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} Excess is in percentage points of annualised return. "
    r"Newey--West $t$-statistics on the daily excess series are reported in "
    r"Appendix Table~\ref{tab:layer1-t}. Layer 1 is the only \emph{inference} layer in which test "
    r"statistics are reported; the attribution tables also carry them, as spanning diagnostics rather "
    r"than inference (Table~\ref{tab:layers}). This design is underpowered by construction "
    r"(see Section~\ref{sec:power}). "
    r"The three as-of pools overlap heavily and are \emph{not} independent samples.",
    r"\end{minipage}",
    r"\end{table}",
    "",
]

# ------------------------------------------------------------------ Appendix: funnel + t-stats
lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Layer 1 point-in-time funnel and test statistics.} Firm counts use only "
    r"filings submitted strictly before the as-of date.}",
    r"\label{tab:layer1-t}",
    r"\begin{tabular}{lrrr}",
    r"\toprule",
    r"& " + " & ".join(L1["as_of_dates"]) + r" \\",
    r"\midrule",
]
rows = [("Filings on file", "filings_on_file"), ("Firms on file", "firms_on_file"),
        (r"Firms with $\geq 2$ fiscal years", "firms_with_2plus_periods"),
        ("Firms screenable", "firms_screenable"),
        ("Passing the quality gate", "passed_quality_gate"),
        ("With a usable price series", "with_price_series")]
for lab, key in rows:
    lines.append(lab + " & " + " & ".join("{:,}".format(L1["funnels"][a][key]) for a in L1["as_of_dates"]) + r" \\")
lines.append("Measurement start & " + " & ".join(L1["funnels"][a]["measurement_start"]
                                                 for a in L1["as_of_dates"]) + r" \\")
lines.append(r"\midrule")
lines.append(r"\multicolumn{4}{l}{\textit{Newey--West $t$ on daily excess vs.\ TOPIX}} \\")
for k in ORDER:
    cells = []
    for a in L1["as_of_dates"]:
        v = L1["results"][a].get(k)
        cells.append(num(v["t_newey_west"], sign=True) if v else "--")
    lines.append(SERIES_LABEL[k] + " & " + " & ".join(cells) + r" \\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

# ------------------------------------------------------------------ Table 2: Layer 2 randomisation
L2 = json.load(open(ED / "layer2_placebo_v11.json"))
SCHEME_LABEL = {"unstratified": "Unstratified draws", "sector_matched": "Sector-composition matched"}
MET = [("ann_return", "Annualised return", "pct"), ("sharpe", "Sharpe ratio", "num"),
       ("max_drawdown", "Maximum drawdown", "pct"), ("beta_vs_topix", r"$\beta$ vs.\ TOPIX", "num")]

lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Layer 2 (randomisation).} The actual portfolio against %s draws of %d firms "
    r"from the same %s-firm 2026 guard-passing pool. Equal weights on both sides. Seed %s. "
    r"Percentiles only: this layer reports no test statistics, because the portfolio embeds 2026 "
    r"hindsight by construction.}"
    % ("{:,}".format(L2["n_draws"]).replace(",", r"{,}"), L2["n_holdings"],
       "{:,}".format(L2["pool_size"]).replace(",", r"{,}"), str(L2["seed"])),
    r"\label{tab:layer2}",
    r"\begin{tabular}{llrrrrrr}",
    r"\toprule",
    r"Draw scheme & Metric & \multicolumn{5}{c}{Placebo distribution} & Actual \\",
    r"\cmidrule(lr){3-7}",
    r"& & p5 & p25 & p50 & p75 & p95 & (pctile) \\",
    r"\midrule",
]
for scheme in ["unstratified", "sector_matched"]:
    first = True
    for key, lab, kind in MET:
        d = L2["distribution"][scheme][key]
        a = L2["actual"]["ours_equal"][key]
        p = L2["percentiles"][scheme]["ours_equal"][key]
        fmt = (lambda x: pct(x) + r"\%") if kind == "pct" else (lambda x: num(x))
        head = r"\multirow{4}{*}{\shortstack[l]{%s}}" % SCHEME_LABEL[scheme].replace(" ", r"\\") if first else ""
        lines.append(" & ".join([head, lab] + [fmt(d[q]) for q in ["p5", "p25", "p50", "p75", "p95"]]
                                + [r"\textbf{%s} (%.1f)" % (fmt(a), p)]) + r" \\")
        first = False
    lines.append(r"\midrule" if scheme == "unstratified" else r"\bottomrule")
lines += [
    r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} Sector matching draws, for each 33-sector code, the same number of firms the "
    r"actual portfolio holds in that sector. Moving from unstratified to sector-matched draws raises "
    r"the median placebo return from " + pct(L2["distribution"]["unstratified"]["ann_return"]["p50"])
    + r"\% to " + pct(L2["distribution"]["sector_matched"]["ann_return"]["p50"])
    + r"\%, i.e.\ sector composition alone accounts for a large part of the gap to the pool. "
    r"The portfolio also sits at the extreme of the $\beta$ and drawdown distributions, so its "
    r"position on the return distribution is not risk-neutral.",
    r"\end{minipage}",
    r"\end{table}",
    "",
]

# ------------------------------------------------------------------ Table 3: factor attribution
FA = json.load(open(ED / "factors_v11.json"))
FACS = ["MKT", "QMJ", "SIZE", "MOM", "SECTOR"]
PORT_LABEL = {"ours_equal": "Portfolio (equal wt.)",
              "benchmark_buf20_equal": "Mechanical benchmark"}
SPEC_LABEL = {"capm": "CAPM", "capm_sector": r"CAPM${+}$sector", 
              "mkt_qmj_size_mom": "Four factors", "full_with_sector": "Five factors"}
HEADLINE = FA.get("headline_spec", "capm_sector")

lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Attribution (hindsight-formed portfolio).} \emph{Factor attribution, monthly, "
    r"%d months.} Factors are built point-in-time from "
    r"the filing panel: QMJ sorts on ROE, SIZE on total assets (an accounting-size proxy, \emph{not} "
    r"market capitalisation), MOM on the 12-1 month return, SECTOR is equal-weighted %s minus the "
    r"equal-weighted universe. \textbf{There is no value factor}: a book-to-market sort needs a share "
    r"count, which this data does not contain point-in-time. Newey--West $t$ (lag %d) in parentheses.}"
    % (FA["sample"]["n_months"], FA["sector_factor"], FA["nw_lag"]),
    r"\label{tab:factors}",
    r"\begin{tabular}{l" + "r" * 4 + r"}",
    r"\toprule",
    r"& \multicolumn{2}{c}{Portfolio (equal wt.)} & \multicolumn{2}{c}{Mechanical benchmark} \\",
    r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
    r"& \textbf{CAPM${+}$sector} & Five factors & \textbf{CAPM${+}$sector} & Five factors \\",
    r"& \scriptsize(headline) & \scriptsize(robustness) & \scriptsize(headline) & "
    r"\scriptsize(robustness) \\",
    r"\midrule",
]
cells = [(p, sp) for p in ["ours_equal", "benchmark_buf20_equal"]
         for sp in [HEADLINE, "full_with_sector"]]
r_of = lambda p, sp: FA["regressions"][p][sp]
lines.append(r"$\alpha$ (annualised) & "
             + " & ".join(pct(r_of(p, sp)["alpha_annualised"], sign=True) + r"\%" for p, sp in cells) + r" \\")
lines.append(r" & " + " & ".join("(%s)" % num(r_of(p, sp)["alpha_t_newey_west"], sign=True)
                                for p, sp in cells) + r" \\")
lines.append(r"\midrule")
for f in FACS:
    row, trow = [], []
    for p, sp in cells:
        r = r_of(p, sp)
        row.append(num(r["loadings"][f]) if f in r["loadings"] else "--")
        trow.append("(%s)" % num(r["loading_t"][f], sign=True) if f in r["loadings"] else "")
    lines.append(f + " & " + " & ".join(row) + r" \\")
    lines.append(" & " + " & ".join(trow) + r" \\")
lines.append(r"\midrule")
lines.append(r"Adjusted $R^2$ & " + " & ".join(num(r_of(p, sp)["adj_r_squared"]) for p, sp in cells) + r" \\")
lines.append(r"\midrule")
lines.append(r"\multicolumn{5}{l}{\textit{$\alpha$ (annualised) across every specification we ran}} \\")
for sp in ["capm", "capm_sector", "mkt_qmj_size_mom", "full_with_sector"]:
    a_o = r_of("ours_equal", sp)
    a_b = r_of("benchmark_buf20_equal", sp)
    lines.append(r"\quad %s (%d regressor%s) & \multicolumn{2}{c}{%s\%% (%s)} & "
                 r"\multicolumn{2}{c}{%s\%% (%s)} \\"
                 % (SPEC_LABEL[sp], len(a_o["factors"]), "" if len(a_o["factors"]) == 1 else "s",
                    pct(a_o["alpha_annualised"], sign=True), num(a_o["alpha_t_newey_west"], sign=True),
                    pct(a_b["alpha_annualised"], sign=True), num(a_b["alpha_t_newey_west"], sign=True)))
lines += [
    r"\bottomrule",
    r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} \textbf{The headline specification is CAPM${+}$sector}, chosen on degrees of "
    r"freedom alone and fixed before the estimates were inspected: 36 monthly observations do not "
    r"support five regressors. The choice is not self-serving --- the five-factor $\alpha$ is "
    r"\emph{larger}, so preferring the parsimonious model lowers the $\alpha$ we report. "
    r"The regressions are run on portfolios formed with 2026 information, so these "
    r"alphas measure how much in-sample excess return tradable factor exposures span --- not skill. "
    r"Two features matter for the paper's calibration. The sector loading is large and the portfolio's "
    r"alpha does \emph{not} vanish once it is included; but the mechanical benchmark, built from the "
    r"same gate with no discretionary step, earns a \emph{larger} alpha under the headline model ("
    + pct(r_of("benchmark_buf20_equal", HEADLINE)["alpha_annualised"], sign=True)
    + r"\% vs.\ " + pct(r_of("ours_equal", HEADLINE)["alpha_annualised"], sign=True)
    + r"\%) and under every specification in the lower panel. "
      r"And the quality factor the screen sorts on returned "
    + pct(FA["factor_summary"]["QMJ"]["annualised"], sign=True)
    + r"\% annualised over the sample, consistent with the Layer 1 null. With "
    + str(FA["sample"]["n_months"])
    + r" monthly observations spanning one regime, every alpha here is fragile --- the headline model "
      r"keeps only two regressors precisely because five is more than this sample supports; see "
      r"Section~\ref{sec:costs}.",
    r"\end{minipage}",
    r"\end{table}",
    "",
]

# ------------------------------------------------------------------ Table 4: benchmark degrees of freedom
CC = json.load(open(ED / "control_comparison_v10.json"))
SENS = CC["sensitivity"]
WEIGHT_LABEL = {"期首加重": "Start-of-window cap.\\ weighted",
                "期末加重": "End-of-window cap.\\ weighted",
                "等金額": "Equal weighted"}
HOLD_LABEL = {"12社": "12", "15社": "15", "20社": "20"}


def sens_rows():
    for key, v in SENS.items():
        n_lab, w_lab = key.split("_", 1)
        yield HOLD_LABEL.get(n_lab, n_lab), WEIGHT_LABEL.get(w_lab, w_lab), v["3y"]


sens_ann = [r["ann_return"] for _, _, r in sens_rows()]
lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Layer 3 (descriptive): the benchmark is a distribution.} The same pool and the "
    r"same quality gate, varying only two ordinary construction choices --- how many firms to hold and "
    r"how to weight them. Three-year annualised returns to 2026-06-01.}",
    r"\label{tab:dof}",
    r"\begin{tabular}{llrrrr}",
    r"\toprule",
    r"Holdings & Weighting & Ann.\ return & Sharpe & MDD & $\beta$ \\",
    r"\midrule",
]
for n_lab, w_lab, r in sens_rows():
    lines.append(" & ".join([n_lab, w_lab, pct(r["ann_return"]) + r"\%", num(r["sharpe"]),
                             pct(r["max_drawdown"]) + r"\%", num(r["beta_vs_topix"])]) + r" \\")
lines += [
    r"\midrule",
    r"\multicolumn{2}{l}{\textbf{Range across the %d variants}} & \textbf{%s\%%--%s\%%} & & & \\"
    % (len(sens_ann), pct(min(sens_ann)), pct(max(sens_ann))),
    r"\bottomrule",
    r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} Descriptive statistics only. The spread of "
    + ("%.1f" % (float(pct(max(sens_ann))) - float(pct(min(sens_ann)))))
    + r" percentage points is produced entirely by construction choices a researcher makes after the "
      r"pool is fixed --- not by any difference in the firms available to hold.",
    r"\end{minipage}",
    r"\end{table}",
    "",
]

# ------------------------------------------------------------------ Table 5: costs and DSR
CO = json.load(open(ED / "costs_v11.json"))
# V11_PLAN W4: the daily fixed-weight convention belongs in the appendix, not the main table.
CONV = [("monthly_rebalance_no_cost", r"Monthly rebalancing, no cost"),
        ("monthly_headline", r"\textbf{Monthly rebalancing, %d bp + %d bp odd lot} \emph{(headline)}"
                            % (int(CO["conventions"]["one_way_bp"]), int(CO["conventions"]["odd_lot_bp"])))]
CPORT = [("ours_equal", "Portfolio"), ("benchmark_buf20_equal", "Mech.\\ benchmark")]

lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Attribution (hindsight-formed portfolio).} \emph{Implementation cost and the "
    r"deflated Sharpe ratio.} Costs are charged on traded "
    r"notional (buys plus sells) with an entry cost on the full notional. The deflated Sharpe ratio "
    r"discounts the observed Sharpe for %d enumerated specifications and for non-normality "
    r"\citep{BaileyLopezdePrado2014}.}" % CO["specification_count"]["total"],
    r"\label{tab:costs}",
    r"\begin{tabular}{lrrrr}",
    r"\toprule",
    r"& \multicolumn{2}{c}{Portfolio} & \multicolumn{2}{c}{Mech.\ benchmark} \\",
    r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
    r"Convention & Ann.\ ret. & Sharpe & Ann.\ ret. & Sharpe \\",
    r"\midrule",
]
for key, lab in CONV:
    cells = []
    for p, _ in CPORT:
        b = CO["results"][p][key]
        cells += [pct(b["ann_return"]) + r"\%", num(b["sharpe"])]
    lines.append(lab + " & " + " & ".join(cells) + r" \\")
lines += [
    r"\midrule",
    r"Annualised turnover (monthly) & "
    + " & ".join("%s$\\times$ & --" % num(CO["results"][p]["annual_turnover_monthly"]) for p, _ in CPORT)
    + r" \\",
    r"\midrule",
    r"\multicolumn{5}{l}{\textit{Deflated Sharpe ratio on the headline series (arithmetic Sharpe; see "
    r"note)}} \\",
]
dsr_rows = [("observed_sharpe_annualised", "Observed Sharpe (arithmetic)", "num"),
            ("threshold_sharpe_annualised", "Threshold Sharpe from %d trials"
             % CO["specification_count"]["total"], "num"),
            ("deflated_sharpe_probability", "Deflated Sharpe probability", "num3")]
for key, lab, kind in dsr_rows:
    cells = []
    for p, _ in CPORT:
        v = CO["deflated_sharpe"][p]["sector_matched_trial_sd"][key]
        cells += ["", ("%.3f" % v) if kind == "num3" else num(v)]
    lines.append(lab + " & " + " & ".join(cells) + r" \\")
lines += [
    r"\bottomrule",
    r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} The contest edition's daily fixed-weight convention, which is not "
    r"implementable, is reported in Appendix Table~\ref{tab:cost-sens} together with the full cost "
    r"grid. Costs barely matter here, and we report that rather than claiming a robustness "
    r"win: annualised turnover under monthly rebalancing is only "
    + num(CO["results"]["ours_equal"]["annual_turnover_monthly"])
    + r"$\times$, so the headline convention costs the portfolio "
    + pct(CO["results"]["ours_equal"]["daily_rebalance_no_cost"]["ann_return"]
          - CO["results"]["ours_equal"]["monthly_headline"]["ann_return"])
    + r" percentage points relative to the contest convention. "
      r"\textbf{The Sharpe ratio in this table is arithmetic} (mean/sd of daily net returns, "
      r"annualised), because that is what the deflated Sharpe formula is defined on; it is lower than "
      r"the geometric Sharpe of "
    + num(CO["results"]["ours_equal"]["monthly_headline"]["sharpe"])
    + r" reported in Tables~\ref{tab:layer2} and~\ref{tab:dof}. The deflated Sharpe survives at the "
      r"95\% level --- but so does the mechanical benchmark's, and both series embed 2026 hindsight, so "
      r"this is a statement about dispersion in the pool, not about skill.",
    r"\end{minipage}",
    r"\end{table}",
    "",
]

# ------------------------------------------------------------------ Table 6/7: saturation and ladder
SA = json.load(open(ED / "saturation_v11.json"))
sat, lad = SA["saturation"], SA["evidence_ladder"]

lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Measurement audit (no inference layer).} \emph{Saturation of a "
    r"thematic-exposure measure.} This table makes no claim about returns. All %s listed firms in the "
    r"cross-section, scored by the composite AI-exposure index inherited by our own pipeline.}"
    % "{:,}".format(sat["n_firms"]).replace(",", r"{,}"),
    r"\label{tab:saturation}",
    r"\begin{tabular}{lr}",
    r"\toprule",
    r"\multicolumn{2}{l}{\textit{Resolution}} \\",
    r"Firms scored & %s \\" % "{:,}".format(sat["n_firms"]).replace(",", r"{,}"),
    r"Distinct score values & %d \\" % sat["n_distinct_values"],
    r"Effective number of levels (inverse Herfindahl) & %s \\" % num(sat["effective_number_of_levels"]),
    r"Five largest ties, share of cross-section & %s\%% \\" % pct(sat["top5_tie_coverage_share"]),
    r"Firms exactly at their sector's median score & %s\%% \\"
    % pct(sat["sector_determinism"]["share_exactly_at_sector_median"]),
    r"Single-valued sectors & %d of %d \\" % (sat["sector_determinism"]["single_valued_sectors"],
                                              sat["sector_determinism"]["n_sectors"]),
    r"\midrule",
    r"\multicolumn{2}{l}{\textit{The largest tie at the top: %d firms at a score of %s, with %d firms above}} \\"
    % (sat["example_cluster"]["n_firms_tied"], num(sat["example_cluster"]["score_value"], 4),
       sat["example_cluster"]["n_firms_strictly_above"]),
]
for f in sat["example_cluster"]["firms"]:
    lines.append(r"\quad %s \textit{(%s)} & --- \\" % (f["name"].replace("&", r"\&"), f["business"]))
lines += [
    r"\midrule",
    r"\multicolumn{2}{l}{\textit{Mechanism}} \\",
    r"Keyword match reads disclosure text? & \textbf{No} \\",
    r"Fields matched & metadata only\rlap{$^{a}$} \\",
    r"R\&D intensity (weight 0.25) populated for & %d of %s firms \\"
    % (sat["mechanism"]["rd_ratio_non_missing"], "{:,}".format(sat["n_firms"]).replace(",", r"{,}")),
    r"\bottomrule",
    r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"$^{a}$ Company name, 33-sector label, 17-sector label, market segment, scale category; plus a "
    r"hard-coded additive bonus for membership in designated sectors. Since the sector label is both a "
    r"matched field and a bonus trigger, sector enters twice, and no remaining input varies across "
    r"firms within a sector.",
    r"\end{minipage}",
    r"\end{table}",
    "",
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Measurement audit (no inference layer).} \emph{The evidence ladder, and what "
    r"our own portfolio scores on it.} %s. Levels 0 and 1 are assigned "
    r"by script; levels 2 and 3 each carry a source URL, source type, and quoted passage.}"
    % lad["pool"],
    r"\label{tab:ladder}",
    r"\begin{tabular}{llrr}",
    r"\toprule",
    r"Level & Requirement & Firms & Share \\",
    r"\midrule",
    r"\multicolumn{4}{l}{\textit{Panel A: the candidate pool}} \\",
]
LADDER_ROWS = [("0", "No thematic keyword link", "0_no_thematic_link"),
               ("1", "Keyword hit only; no artefact", "1_keyword_hit_only"),
               ("2", "Named product, customer, or committed investment", "2_named_product_or_customer"),
               ("3", "Disclosed quantity attributable to the theme", "3_disclosed_quantity")]
for lvl, req, key in LADDER_ROWS:
    n = lad["levels"][key]
    lines.append(r"%s & %s & %s & %s\%% \\"
                 % (lvl, req, "{:,}".format(n).replace(",", r"{,}"), pct(n / lad["pool_size"])))
lines += [
    r"\midrule",
    r"\multicolumn{2}{l}{Verified by hand (levels 2--3)} & %d & %s\%% \\"
    % (lad["curated_count"], pct(lad["curated_count"] / lad["pool_size"])),
    r"\multicolumn{2}{l}{Discarded as keyword-only} & %s & \\"
    % "{:,}".format(lad["keyword_only_rejected"]).replace(",", r"{,}"),
    r"\midrule",
    r"\multicolumn{4}{l}{\textit{Panel B: the same ladder applied to the %d holdings this paper "
    r"studies}} \\" % SA["own_portfolio_audit"]["n_holdings"],
]
_oa = SA["own_portfolio_audit"]
_ol = _oa["thematic_level_distribution"]
for lvl, req, key in [("0", "No thematic keyword link", "0"), ("1", "Keyword hit only", "1"),
                      ("2", "Named product or customer", "2"),
                      ("3", "Disclosed quantity", "3")]:
    n = int(_ol.get(key, 0))
    lines.append(r"%s & %s & %d & %s\%% \\" % (lvl, req, n, pct(n / _oa["n_holdings"])))
lines.append(r"--- & \emph{Never scored (outside the pool)} & %d & %s\%% \\"
             % (len(_oa["absent_from_candidate_pool_file"]),
                pct(len(_oa["absent_from_candidate_pool_file"]) / _oa["n_holdings"])))
lines += [
    r"\bottomrule",
    r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} The ladder's discriminating power is concentrated in the %d firms where a human "
    r"opened a document. The %s discarded firms' filings were \emph{not} read; they are the residual "
    r"after hand verification, not a population that was inspected and rejected. The ladder is "
    r"\textbf{not validated} as a predictor --- see Section~\ref{sec:ladder-validation} for what a "
    r"validation would require." % (lad["curated_count"],
                                    "{:,}".format(lad["keyword_only_rejected"]).replace(",", r"{,}")),
    r"\end{minipage}",
    r"\end{table}",
    "",
]

# ------------------------------------------------------------------ Appendix tables
AP = json.load(open(ED / "appendix_v11.json"))
rob, cs, corr = AP["robustness"], AP["cost_sensitivity"], AP["evidence_correspondence"]

lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    # NOT Layer 1: this perturbs thresholds on the 2026 snapshot and compares the resulting
    # selections. There is no forward measurement, so it is descriptive.
    r"\caption{\textbf{Layer 3 (descriptive).} \emph{Gate-threshold stability of the mechanical "
    r"selection.} Each variant perturbs exactly one threshold and re-runs the selection on the 2026 "
    r"snapshot; there is no forward measurement here. Overlap counts how many of the %d base holdings "
    r"survive.}" % len(rob["base_selection"]),
    r"\label{tab:robustness}",
    r"\begin{tabular}{lc}",
    r"\toprule",
    r"Variant (one threshold changed) & Overlap with base \\",
    r"\midrule",
]
VAR_EN = {"ＲＯＥ閾値 12%": r"ROE threshold $\geq$12\%", "ＲＯＥ閾値 18%": r"ROE threshold $\geq$18\%",
          "営業利益率 5%": r"Operating margin $\geq$5\%", "自己資本比率 40%": r"Equity ratio $\geq$40\%",
          "増収増益ゲート外す": "Drop the revenue/profit-growth gate",
          "無赤字ゲート外す": "Drop the loss-free gate", "順位=ＲＯＥのみ": "Rank on ROE alone",
          "同一業種上限 3": "Sector cap raised to 3"}
for v in rob["variants"]:
    lines.append("%s & %d of %d \\\\" % (VAR_EN.get(v["variant"], v["variant"]),
                                       v["overlap_with_base"], len(rob["base_selection"])))
lines += [
    r"\midrule",
    r"\textbf{Minimum overlap across all %d variants} & \textbf{%d of %d} \\"
    % (rob["n_variants"], rob["min_overlap"], len(rob["base_selection"])),
    r"\bottomrule", r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} Stability here is a property of the \emph{selection rule} on one snapshot, not "
    r"evidence about returns. The mechanical selection is stable to single-threshold perturbation: at least "
    r"%d of %d holdings survive every variant. This says the \emph{selection} is not knife-edge; it "
    r"says nothing about whether the selection has forward-looking content, which "
    r"Table~\ref{tab:layer1} addresses and answers in the negative."
    % (rob["min_overlap"], len(rob["base_selection"])),
    r"\end{minipage}", r"\end{table}", "",
]

# --- cost sensitivity (including the daily conventions moved out of the main table)
GRID = [k for k in CO["results"]["ours_equal"]["cost_grid_monthly"]]
lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Attribution (hindsight-formed portfolio).} \emph{Cost sensitivity and the "
    r"contest edition's daily convention.} Three-year annualised returns. The odd-lot spread of %d bp "
    r"is added to every one-way cost in the grid.}" % int(CO["conventions"]["odd_lot_bp"]),
    r"\label{tab:cost-sens}",
    r"\begin{tabular}{l" + "r" * (len(GRID) + 3) + r"}",
    r"\toprule",
    r"& \multicolumn{%d}{c}{Monthly rebalancing, one-way cost} & "
    r"\multicolumn{2}{c}{Daily rebalancing} & Turnover \\" % len(GRID),
    r"\cmidrule(lr){2-%d}\cmidrule(lr){%d-%d}" % (len(GRID) + 1, len(GRID) + 2, len(GRID) + 3),
    "Series & " + " & ".join(g.replace("bp", " bp") for g in GRID)
    + r" & no cost & headline & (monthly) \\",
    r"\midrule",
]
for row in cs:
    cells = [pct(row["monthly_" + g]) + r"\%" for g in GRID]
    cells += [pct(row["daily_no_cost"]) + r"\%", pct(row["daily_headline_cost"]) + r"\%",
              num(row["annual_turnover_monthly"]) + r"$\times$"]
    lines.append(row["series"] + " & " + " & ".join(cells) + r" \\")
lines += [
    r"\bottomrule", r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} The daily fixed-weight convention is the contest edition's and is not "
    r"implementable; it appears here rather than in the main text. Even a %d bp one-way assumption "
    r"leaves the ranking of the two series unchanged, which is why Section~\ref{sec:costs} declines to "
    r"treat cost robustness as a result." % int(max(CO["conventions"]["cost_grid_bp"])),
    r"\end{minipage}", r"\end{table}", "",
]

# --- evidence level vs realised revenue growth
LV = sorted(corr["by_level"], key=int)
lines += [
    r"\begin{table}[htbp]",
    r"\centering\small",
    r"\caption{\textbf{Measurement audit (no inference layer).} \emph{Evidence level against realised "
    r"revenue growth --- the result runs against our own proposal.} The %d hand-coded firms; annualised "
    r"total revenue growth across the fiscal years on file.}" % sum(corr["by_level"][l]["n"] for l in LV),
    r"\label{tab:correspondence}",
    r"\begin{tabular}{lrrrr}",
    r"\toprule",
    r"Evidence level & $n$ & Median & Mean & Range \\",
    r"\midrule",
]
for l in LV:
    b = corr["by_level"][l]
    lines.append(r"Level %s & %d & %s\%% & %s\%% & %s\%% to %s\%% \\"
                 % (l, b["n"], pct(b["median_revenue_cagr"], sign=True),
                    pct(b["mean_revenue_cagr"], sign=True),
                    pct(b["min"], sign=True), pct(b["max"], sign=True)))
lines += [
    r"\bottomrule", r"\end{tabular}",
    r"\begin{minipage}{\textwidth}\vspace{2pt}\scriptsize",
    r"\textit{Notes.} \textbf{Level-3 firms grew revenue more slowly than level-2 firms over this "
    r"window.} We report this rather than omit it. It is not evidence that the ladder fails and we "
    r"would resist a reader concluding either way: the cells hold %d and %d firms, the measure is "
    r"\emph{total} revenue rather than theme-attributable revenue (which almost no firm discloses "
    r"separately), the levels were not coded as-of, and nothing controls for sector or size. The table "
    r"has no power to order the levels --- which is precisely the point made in "
    r"Section~\ref{sec:ladder-validation}." % (corr["by_level"][LV[0]]["n"], corr["by_level"][LV[-1]]["n"]),
    r"\end{minipage}", r"\end{table}", "",
]

# ------------------------------------------------------------------ split tables by section
# A table must float near the text that discusses it. Emitting one monolithic file pushed the
# saturation and ladder tables -- the centre of the paper -- six pages past Section 2.
FILE_OF_LABEL = {
    "tab:layer1": "tables_l1_v11",
    "tab:layer1-t": "tables_appendix_v11",
    "tab:robustness": "tables_appendix_v11",
    "tab:cost-sens": "tables_appendix_v11",
    "tab:correspondence": "tables_appendix_v11",
    "tab:layer2": "tables_l2_v11",
    "tab:factors": "tables_factor_v11",
    "tab:dof": "tables_dof_v11",
    "tab:costs": "tables_costs_v11",
    "tab:saturation": "tables_sat_v11",
    "tab:ladder": "tables_sat_v11",
}

blocks, cur = [], []
for ln in lines:
    if ln.startswith(r"\begin{table}") and cur:
        blocks.append(cur)
        cur = [ln]
    else:
        cur.append(ln)
if cur:
    blocks.append(cur)

files = {}
for b in blocks:
    text = "\n".join(b)
    m = re.search(r"\\label\{(tab:[^}]+)\}", text)
    if not m:
        continue
    files.setdefault(FILE_OF_LABEL[m.group(1)], []).append(text)

HEADER = r"% AUTO-GENERATED by scripts/build_wp_tables_v11.py -- do not edit by hand."
for name, chunks in files.items():
    (ED / (name + ".tex")).write_text(HEADER + "\n" + "\n".join(chunks) + "\n", encoding="utf-8")

# a manifest file keeps the gate checker's "tables_v11" contract and lists what was emitted
(ED / "tables_v11.tex").write_text(
    HEADER + "\n" + "\n".join(r"\input{%s}" % n for n in sorted(files)) + "\n", encoding="utf-8")

# ------------------------------------------------------------------ in-text macros
best = max((L1["results"][a][k]["excess_ann"], a, k)
           for a in L1["as_of_dates"] for k in L1["results"][a])
worst = min((L1["results"][a][k]["excess_ann"], a, k)
            for a in L1["as_of_dates"] for k in L1["results"][a])
n_cells = sum(len(L1["results"][a]) for a in L1["as_of_dates"])
n_negative = sum(1 for a in L1["as_of_dates"] for k in L1["results"][a]
                 if L1["results"][a][k]["excess_ann"] < 0)

macros = {
    "LoneNasof": str(len(L1["as_of_dates"])),
    "LoneCells": str(n_cells),
    "LoneNegative": str(n_negative),
    "LoneBestExcess": pct(best[0], sign=True),
    "LoneWorstExcess": pct(worst[0], sign=True),
    "LoneSpecTotal": str(L1["specification_count"]["total"]),
    "LoneEnd": L1["end"],
    "PanelFilings": "{:,}".format(L1["panel_totals"]["filings"]).replace(",", r"{,}"),
    "PanelFirms": "{:,}".format(L1["panel_totals"]["firms"]).replace(",", r"{,}"),
    "PanelYears": str(L1["panel_totals"]["median_fiscal_years_per_firm"]),
}
for a, tag in zip(L1["as_of_dates"], ["A", "B", "C"]):
    f, res = L1["funnels"][a], L1["results"][a]
    macros["Lone%sDate" % tag] = a
    macros["Lone%sGate" % tag] = "{:,}".format(f["passed_quality_gate"])
    macros["Lone%sScreenable" % tag] = "{:,}".format(f["firms_screenable"]).replace(",", r"{,}")
    macros["Lone%sPoolT" % tag] = num(res["pool_eq"]["t_newey_west"], sign=True)
    macros["Lone%sMonths" % tag] = str(round(res["pool_eq"]["days"] / 21))
    macros["Lone%sTopix" % tag] = pct(res["pool_eq"]["bench_ann_return"])
    macros["Lone%sPoolAnn" % tag] = pct(res["pool_eq"]["ann_return"])
    macros["Lone%sPoolExcess" % tag] = pct(res["pool_eq"]["excess_ann"], sign=True)
    macros["Lone%sPoolBeta" % tag] = num(res["pool_eq"]["beta_vs_bench"])
    macros["Lone%sTopFiveAnn" % tag] = pct(res["shu5_roe_only"]["ann_return"])
    macros["Lone%sTopTwentyAnn" % tag] = pct(res["buf20_roe_only"]["ann_return"])

macros.update({
    # A seed is an identifier, not a quantity: never thousands-separate it, or a reader
    # retyping the printed value gets a different stream.
    "LtwoSeed": str(L2["seed"]),
    "LtwoDraws": "{:,}".format(L2["n_draws"]).replace(",", r"{,}"),
    "LtwoPool": "{:,}".format(L2["pool_size"]).replace(",", r"{,}"),
    "LtwoActualHoldings": str(L2["n_holdings"]),
    "LtwoInsidePool": str(L2["holdings_inside_pool"]),
    "LtwoActualAnn": pct(L2["actual"]["ours_equal"]["ann_return"]),
    "LtwoActualBeta": num(L2["actual"]["ours_equal"]["beta_vs_topix"]),
    "LtwoActualMdd": pct(L2["actual"]["ours_equal"]["max_drawdown"]),
    "LtwoUnstratMedian": pct(L2["distribution"]["unstratified"]["ann_return"]["p50"]),
    "LtwoMatchedMedian": pct(L2["distribution"]["sector_matched"]["ann_return"]["p50"]),
    "LtwoUnstratPctile": "%.1f" % L2["percentiles"]["unstratified"]["ours_equal"]["ann_return"],
    "LtwoMatchedPctile": "%.1f" % L2["percentiles"]["sector_matched"]["ours_equal"]["ann_return"],
    "LtwoMatchedBetaPctile": "%.1f" % L2["percentiles"]["sector_matched"]["ours_equal"]["beta_vs_topix"],
    "LtwoMatchedMddPctile": "%.1f" % L2["percentiles"]["sector_matched"]["ours_equal"]["max_drawdown"],
    "LtwoMatchedBetaMedian": num(L2["distribution"]["sector_matched"]["beta_vs_topix"]["p50"]),
    "FaMonths": str(FA["sample"]["n_months"]),
    "FaFirst": FA["sample"]["first_month"],
    "FaLast": FA["sample"]["last_month"],
    "FaSectorName": FA["sector_factor"],
    "FaQmjAnn": pct(FA["factor_summary"]["QMJ"]["annualised"], sign=True),
    "FaSizeAnn": pct(FA["factor_summary"]["SIZE"]["annualised"], sign=True),
    "FaSectorAnn": pct(FA["factor_summary"]["SECTOR"]["annualised"], sign=True),
    "FaMomAnn": pct(FA["factor_summary"]["MOM"]["annualised"], sign=True),
    "FaOursAlpha": pct(r_of("ours_equal", "full_with_sector")["alpha_annualised"], sign=True),
    "FaHeadOursAlpha": pct(r_of("ours_equal", HEADLINE)["alpha_annualised"], sign=True),
    "FaHeadOursAlphaT": num(r_of("ours_equal", HEADLINE)["alpha_t_newey_west"], sign=True),
    "FaHeadOursSector": num(r_of("ours_equal", HEADLINE)["loadings"]["SECTOR"]),
    "FaHeadOursSectorT": num(r_of("ours_equal", HEADLINE)["loading_t"]["SECTOR"], sign=True),
    "FaHeadOursRtwo": num(r_of("ours_equal", HEADLINE)["adj_r_squared"]),
    "FaHeadBenchAlpha": pct(r_of("benchmark_buf20_equal", HEADLINE)["alpha_annualised"], sign=True),
    "FaHeadBenchAlphaT": num(r_of("benchmark_buf20_equal", HEADLINE)["alpha_t_newey_west"], sign=True),
    "FaGrahamAnn": "13.3",
    "FaGrahamTopix": "24.0",
    "FaOursAlphaT": num(r_of("ours_equal", "full_with_sector")["alpha_t_newey_west"], sign=True),
    "FaOursSector": num(r_of("ours_equal", "full_with_sector")["loadings"]["SECTOR"]),
    "FaOursSectorT": num(r_of("ours_equal", "full_with_sector")["loading_t"]["SECTOR"], sign=True),
    "FaOursCapmAlpha": pct(r_of("ours_equal", "capm")["alpha_annualised"], sign=True),
    "FaBenchAlpha": pct(r_of("benchmark_buf20_equal", "full_with_sector")["alpha_annualised"], sign=True),
    "FaBenchAlphaT": num(r_of("benchmark_buf20_equal", "full_with_sector")["alpha_t_newey_west"], sign=True),
    "FaOursRtwo": num(r_of("ours_equal", "full_with_sector")["adj_r_squared"]),
    "DofMin": pct(min(sens_ann)),
    "DofMax": pct(max(sens_ann)),
    "DofSpread": "%.1f" % (float(pct(max(sens_ann))) - float(pct(min(sens_ann)))),
    "DofVariants": str(len(sens_ann)),
    "SpecTotal": str(CO["specification_count"]["total"]),
    "SpecBreakdown": "; ".join(
        "%d %s" % (row["n"], row["category"][0].lower() + row["category"][1:])
        for row in CO["specification_count"]["table"]),
    "CostOneWay": str(int(CO["conventions"]["one_way_bp"])),
    "CostOddLot": str(int(CO["conventions"]["odd_lot_bp"])),
    "CostTurnover": num(CO["results"]["ours_equal"]["annual_turnover_monthly"]),
    "CostHeadlineAnn": pct(CO["results"]["ours_equal"]["monthly_headline"]["ann_return"]),
    "CostContestAnn": pct(CO["results"]["ours_equal"]["daily_rebalance_no_cost"]["ann_return"]),
    "CostDrag": pct(CO["results"]["ours_equal"]["daily_rebalance_no_cost"]["ann_return"]
                    - CO["results"]["ours_equal"]["monthly_headline"]["ann_return"]),
    "CostGridMax": str(int(max(CO["conventions"]["cost_grid_bp"]))),
    "CostHundredBp": pct(CO["results"]["ours_equal"]["cost_grid_monthly"]["100bp"]["ann_return"]),
    "DsrObserved": num(CO["deflated_sharpe"]["ours_equal"]["sector_matched_trial_sd"]["observed_sharpe_annualised"]),
    "DsrThreshold": num(CO["deflated_sharpe"]["ours_equal"]["sector_matched_trial_sd"]["threshold_sharpe_annualised"]),
    "DsrProb": "%.3f" % CO["deflated_sharpe"]["ours_equal"]["sector_matched_trial_sd"]["deflated_sharpe_probability"],
    "DsrKurtosis": num(CO["deflated_sharpe"]["ours_equal"]["sector_matched_trial_sd"]["kurtosis"]),
    "SatFirms": "{:,}".format(sat["n_firms"]).replace(",", r"{,}"),
    "SatDistinct": str(sat["n_distinct_values"]),
    "SatEffLevels": num(sat["effective_number_of_levels"]),
    "SatTopFiveShare": pct(sat["top5_tie_coverage_share"]),
    "SatSectorShare": pct(sat["sector_determinism"]["share_exactly_at_sector_median"]),
    "SatSingleSectors": str(sat["sector_determinism"]["single_valued_sectors"]),
    "SatSectors": str(sat["sector_determinism"]["n_sectors"]),
    "SatTieN": str(sat["example_cluster"]["n_firms_tied"]),
    "SatTieValue": num(sat["example_cluster"]["score_value"], 4),
    "SatAbove": str(sat["example_cluster"]["n_firms_strictly_above"]),
    "SatRdPresent": str(sat["mechanism"]["rd_ratio_non_missing"]),
    "SatShareCount": "{:,}".format(sat["mechanism"]["shares_outstanding_non_missing"]).replace(",", r"{,}"),
    "SatRdImputed": "{:,}".format(sat["mechanism"]["rd_ratio_imputed_to_zero"]).replace(",", r"{,}"),
    "LadderPool": "{:,}".format(lad["pool_size"]).replace(",", r"{,}"),
    "LadderLzero": str(lad["levels"]["0_no_thematic_link"]),
    "LadderLone": str(lad["levels"]["1_keyword_hit_only"]),
    "LadderLtwo": str(lad["levels"]["2_named_product_or_customer"]),
    "LadderLthree": str(lad["levels"]["3_disclosed_quantity"]),
    "LadderVerified": str(lad["curated_count"]),
    "LadderKeywordOnly": "{:,}".format(lad["keyword_only_rejected"]).replace(",", r"{,}"),
})

oa = SA["own_portfolio_audit"]
_lv = oa["thematic_level_distribution"]
macros.update({
    "OwnHoldings": str(oa["n_holdings"]),
    "OwnPresent": str(oa["in_candidate_pool_file"]),
    "OwnAbsent": str(len(oa["absent_from_candidate_pool_file"])),
    "OwnLevelZero": str(_lv.get("0", 0)),
    "OwnLevelOne": str(_lv.get("1", 0)),
    "OwnLevelTwo": str(_lv.get("2", 0)),
    "OwnVerified": str(oa["n_hand_verified"]),
    "OwnOverlap": str(len(oa["overlap_with_pipeline_final20"])),
})

SV = json.load(open(ED / "survivorship_v11.json"))
macros.update({
    "SurvTickers": "{:,}".format(SV["panel"]["n_tickers"]).replace(",", r"{,}"),
    "SurvStart": SV["panel"]["start"],
    "SurvEnd": SV["panel"]["end"],
    "SurvStopped": str(SV["stopped_series"][str(SV["thresholds_days"][0])]["n_tickers_stopped"]),
    "SurvThreshold": str(SV["thresholds_days"][0]),
})
for a, tag in zip(L1["as_of_dates"], ["A", "B", "C"]):
    m = CO["mde"].get(a)
    if m:
        macros["Mde%s" % tag] = pct(m["mde_annualised"], sign=True)
        macros["Mde%sTe" % tag] = pct(m["tracking_error_annualised"])
        macros["Mde%sDetect" % tag] = "detectable" if m["detectable"] else "below the detection threshold"
macros["MdeNotDetectable"] = str(sum(1 for m in CO["mde"].values() if not m["detectable"]))
macros["LoneRejectFive"] = str(sum(1 for a in L1["as_of_dates"]
                                   if abs(L1["results"][a]["pool_eq"]["t_newey_west"]) >= 1.96))
macros["MdeTotal"] = str(len(CO["mde"]))

out = [r"% AUTO-GENERATED by scripts/build_wp_tables_v11.py -- do not edit by hand."]
out += [r"\newcommand{\%s}{%s}" % (k, v) for k, v in macros.items()]
(ED / "numbers_v11.tex").write_text("\n".join(out) + "\n", encoding="utf-8")

print("wrote tables_v11.tex (%d lines) and numbers_v11.tex (%d macros)" % (len(lines), len(macros)))
print("L1 summary: %d/%d specification cells underperform TOPIX; best %s pp (%s, %s), worst %s pp (%s, %s)"
      % (n_negative, n_cells, pct(best[0], sign=True), best[1], best[2],
         pct(worst[0], sign=True), worst[1], worst[2]))
